apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-mq-uniform-cluster-ibm-mq-uniform-cluster-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-cp-mq-uniform-cluster
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: >-
      payload/2-services/namespace/gitops-cp-mq-uniform-cluster/ibm-mq-uniform-cluster-instance
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-mq-uniform-cluster-ocp4_cp4i.git
    targetRevision: main
    helm:
      releaseName: ibm-mq-uniform-cluster-instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
